### ISSUE TITLE
infrabox push fails for sources >4G

### ISSUE THREAD

**Issue by markwaldkat** [SAP/InfraBox#28]
I'm using infraboxcli 0.6.2.

I executed "infrabox push" in a directory that is larger than 4G and get this error message:

 infrabox push
[infrabox] compressing /path/to/repo
Traceback (most recent call last):
  File "/usr/local/bin/infrabox", line 3, in <module>
    infraboxcli.main()
  File "/usr/local/lib/python2.7/dist-packages/infraboxcli/__init__.py", line 141, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/infraboxcli/push.py", line 99, in push
    zip_file = zipdir(args)
  File "/usr/local/lib/python2.7/dist-packages/infraboxcli/push.py", line 55, in zipdir
    add_files(args, ignore_list, args.project_root, ziph)
  File "/usr/local/lib/python2.7/dist-packages/infraboxcli/push.py", line 32, in add_files
    add_files(args, ignore_list, p, ziph)
  File "/usr/local/lib/python2.7/dist-packages/infraboxcli/push.py", line 32, in add_files
    add_files(args, ignore_list, p, ziph)
  File "/usr/local/lib/python2.7/dist-packages/infraboxcli/push.py", line 28, in add_files
    ziph.write(p, rp)
  File "/usr/lib/python2.7/zipfile.py", line 1141, in write
    self._writecheck(zinfo)
  File "/usr/lib/python2.7/zipfile.py", line 1109, in _writecheck
    raise LargeZipFile("Zipfile size would require ZIP64 extensions")
zipfile.LargeZipFile: Zipfile size would require ZIP64 extensionsh

Solution would be something like this 
zip_archive = zipfile.ZipFile(zip_filename, "w", compression=zipfile.ZIP_DEFLATED, allowZip64=True)

"allowZip64=True" being the important part.

**Comment by iberryful** [comment]
fixed.
https://github.com/SAP/InfraBox-cli/pull/16
